name: teamsync
description: ProjectSync mobile prototype in Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/entry_logo.png
    - assets/images/onboarding_second.jpg
    - assets/images/onboarding_third.jpg
    - assets/images/onboarding_fourth.jpg
