// File generated by FlutterFire CLI configuration for web, Android, and iOS
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// 
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClC8NoCSRcEbyVuSQlBXXCLQ_zkfpO7WA',
    appId: '1:998334623944:web:6641d444cefa816b5cb5fd',
    messagingSenderId: '998334623944',
    projectId: 'teamsync-6a35e',
    authDomain: 'teamsync-6a35e.firebaseapp.com',
    storageBucket: 'teamsync-6a35e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaaNtBNZiBYYPlwnZlrjuHFJgTbwBsRYA',
    appId: '1:998334623944:android:e95f325987ac074f5cb5fd',
    messagingSenderId: '998334623944',
    projectId: 'teamsync-6a35e',
    storageBucket: 'teamsync-6a35e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClC8NoCSRcEbyVuSQlBXXCLQ_zkfpO7WA',
    appId: '1:998334623944:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '998334623944',
    projectId: 'teamsync-6a35e',
    storageBucket: 'teamsync-6a35e.firebasestorage.app',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
      case TargetPlatform.windows:
      case TargetPlatform.macOS:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
